name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    required: true
    description: 'GITHUB_TOKEN'
  merge-method:
    required: false
    description: 'マージ方法(merge,squash,rebase)'
    default: 'merge'
runs:
  using: 'node16'
  main: 'dist/index.js'
