name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    required: true
    description: 'GITHUB_TOKEN'
  pull-number:
    required: true
    description: 'プルリクエストの番号'
runs:
  using: 'node16'
  main: 'dist/index.js'
